source 'https://github.com/CocoaPods/Specs.git'
use_frameworks!

target 'POPViewPager_Example', :exclusive => true do
  pod 'POPViewPager', :path => '../'
end

target 'POPViewPager_Tests', :exclusive => true do
  pod 'POPViewPager', :path => '../'

  
end
